"""S&Y translog: independent derivatives, hurdle data and complete bootstrap."""

from pathlib import Path
import sys
import unittest

import numpy as np
import pandas as pd
from scipy.special import ndtr

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from pyquaidsce import translog
from pyquaidsce.data import DemandData
from pyquaidsce.inference import complex_step_jacobian
from pyquaidsce.selection import (build_selection_design, selection_index,
                                  selection_layout)
from pyquaidsce.translog_model import (TranslogCoefs, TranslogSpec, delta_matrix,
    elasticities, fitted_shares, fitted_share_derivatives, full_vector,
    jacobian_free, latent_shares, pack, share_derivatives, unpack)


def censored_sample(size=700, seed=124):
    """Bivariate-normal selection/outcome errors with a known S&Y mean.

    Responses are generated by actual participation draws, not by fitting a
    copy of the transformed regression. Latent coefficients deliberately do
    not add up. Observed responses need not add up in this unrestricted DGP.
    """
    rng = np.random.default_rng(seed)
    lp = rng.normal(0, .45, (size, 3))
    lm = rng.normal(2.5, .55, size)
    z = rng.normal(.3, .5, size)
    alpha = np.array([.31, .28, .35])
    gamma = np.array([[.008, -.003, .002], [-.003, -.006, .001], [.002, .001, .004]])
    nu = np.array([.01, -.005, .008])
    delta = np.array([.006, .004, .005])
    t = np.exp(lp-lm[:, None])*z[:, None]*nu
    b = 1-t.sum(axis=1)
    r = lp-lm[:, None]-np.log(b)[:, None]
    gr = r @ gamma.T
    latent = t+b[:, None]*(alpha+gr)/(1+gr.sum(axis=1))[:, None]
    kp = np.array([[.35, -.10, .15], [-.20, .30, .12], [.15, -.10, .25]])
    k = lp @ kp.T + lm[:, None]*np.array([.14, -.08, .10])
    k += z[:, None]*np.array([.18, -.13, .12])+np.array([-.4, .1, -.2])
    u = rng.normal(size=(size, 3))
    selected = k+u > 0
    w = selected*(latent+u*delta+rng.normal(0, .01, (size, 3)))
    if np.any(w < 0) or np.any(w > 1):
        raise AssertionError("invalid hurdle sample calibration")
    frame = pd.DataFrame({**{f"p{i+1}": np.exp(lp[:, i]) for i in range(3)},
        **{f"w{i+1}": w[:, i] for i in range(3)}, "m": np.exp(lm), "z": z})
    spec = TranslogSpec(3, 1, True)
    theta = pack(TranslogCoefs(alpha, gamma, nu[:, None], delta), spec)
    pdf = np.exp(-.5*k*k)/np.sqrt(2*np.pi)
    expected = ndtr(k)*latent+delta*pdf
    return frame, theta, expected


OPTIONS = dict(shares=["w1", "w2", "w3"], prices=["p1", "p2", "p3"],
               expenditure="m", demographics=["z"], censor=True, verbose=False)


class TranslogSYMathTests(unittest.TestCase):
    def setUp(self):
        self.frame, self.theta, _ = censored_sample(size=32)
        self.spec = TranslogSpec(3, 1, True)
        self.layout = selection_layout(OPTIONS["prices"], ["p3", "p1"], ["z"], include_expenditure=True)
        lp = np.log(self.frame[OPTIONS["prices"]].to_numpy())
        lm = np.log(self.frame.m.to_numpy())
        z = self.frame[["z"]].to_numpy()
        self.X = build_selection_design(lp, lm, z, self.layout)
        self.tau = np.array([[.18, -.08, .12, .14, -.3],
                             [-.12, .22, -.08, -.13, .1],
                             [.15, -.06, .1, .12, -.2]]).ravel()
        self.k = selection_index(self.X, self.tau, self.layout, 3)
        self.d = DemandData(lp, lm, self.frame[OPTIONS["shares"]].to_numpy(), z,
            ndtr(self.k), np.exp(-.5*self.k**2)/np.sqrt(2*np.pi))

    def test_free_alpha_mapping_and_all_equation_jacobian(self):
        self.assertEqual(self.spec.n_free, 15)
        self.assertEqual(self.spec.n_eq_estimated, 3)
        c = unpack(self.theta, self.spec)
        self.assertAlmostEqual(c.alpha.sum(), .94)
        np.testing.assert_allclose(pack(c, self.spec), self.theta)
        np.testing.assert_allclose(full_vector(self.theta, self.spec), self.theta)
        np.testing.assert_allclose(delta_matrix(self.spec), np.eye(15))
        numeric = complex_step_jacobian(lambda t: fitted_shares(t, self.d, self.spec), self.theta)
        numeric = numeric.reshape(self.d.nobs, 3, -1)
        analytic = jacobian_free(self.theta, self.d, self.spec)
        np.testing.assert_allclose(analytic, numeric, atol=5e-13)
        np.testing.assert_allclose(jacobian_free(self.theta, self.d, self.spec, slice(5, 10)), analytic[5:10])
        self.assertGreater(np.max(abs(analytic[:, 2, 2])), .1)
        self.assertGreater(np.max(abs(latent_shares(self.theta, self.d, self.spec).sum(axis=1)-1)), .01)

    def test_final_quantity_elasticities_against_input_perturbations(self):
        dm, dp = fitted_share_derivatives(self.theta, self.d, self.spec,
            tau=self.tau, layout=self.layout, selection_index=self.k)
        el = elasticities(self.theta, self.d, self.spec, tau=self.tau,
                          layout=self.layout, selection_index=self.k)
        h = 1e-6
        def observed(lp, lm):
            X = build_selection_design(lp, lm, self.d.demo, self.layout)
            k = selection_index(X, self.tau, self.layout, 3)
            d = DemandData(lp, lm, self.d.shares, self.d.demo, ndtr(k),
                          np.exp(-.5*k*k)/np.sqrt(2*np.pi))
            w = fitted_shares(self.theta, d, self.spec)
            return w, np.exp(lm[:, None]-lp)*w
        plus, qp = observed(self.d.lnp, self.d.lnexp+h)
        minus, qm = observed(self.d.lnp, self.d.lnexp-h)
        np.testing.assert_allclose(dm, (plus-minus)/(2*h), atol=2e-9)
        np.testing.assert_allclose(el.income, (np.log(qp)-np.log(qm))/(2*h), atol=2e-8)
        for j in range(3):
            lp, lm = self.d.lnp.copy(), self.d.lnp.copy()
            lp[:, j] += h
            lm[:, j] -= h
            plus, qp = observed(lp, self.d.lnexp)
            minus, qm = observed(lm, self.d.lnexp)
            np.testing.assert_allclose(dp[:, :, j], (plus-minus)/(2*h), atol=2e-9)
            np.testing.assert_allclose(el.uncompensated[:, :, j], (np.log(qp)-np.log(qm))/(2*h), atol=2e-8)
            _, qp = observed(lp, self.d.lnexp+h*el.we[:, j])
            _, qm = observed(lm, self.d.lnexp-h*el.we[:, j])
            np.testing.assert_allclose(el.compensated[:, :, j], (np.log(qp)-np.log(qm))/(2*h), atol=2e-8)
        # Price 2 is absent from the selection design: only its latent derivative remains.
        latent_dp = share_derivatives(self.theta, self.d, self.spec)[1]
        np.testing.assert_allclose(dp[:, :, 1], self.d.cdf*latent_dp[:, :, 1], atol=1e-14)

    def test_uncensored_limit_and_index_consistency(self):
        old_spec = TranslogSpec(3, 1)
        old = pack(TranslogCoefs(np.array([.31, .28, .41]), unpack(self.theta, self.spec).gamma,
                                unpack(self.theta, self.spec).nu), old_spec)
        lifted = pack(unpack(old, old_spec), self.spec)
        d = self.d.subset(slice(None))
        k = np.full((d.nobs, 3), 40.)
        d.cdf, d.pdf = ndtr(k), np.exp(-.5*k*k)/np.sqrt(2*np.pi)
        actual = elasticities(lifted, d, self.spec, tau=np.zeros_like(self.tau),
                              layout=self.layout, selection_index=k)
        expected = elasticities(old, d, old_spec)
        for name in ("income", "uncompensated", "compensated", "we"):
            np.testing.assert_allclose(getattr(actual, name), getattr(expected, name), atol=1e-13)
        with self.assertRaisesRegex(ValueError, "xb"):
            fitted_share_derivatives(self.theta, self.d, self.spec, tau=self.tau,
                                     layout=self.layout, selection_index=np.zeros_like(k))


class TranslogSYEstimationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.frame, cls.truth, cls.expected = censored_sample()
        cls.fit = translog(cls.frame, **OPTIONS)

    def test_hurdle_fit_predictions_and_conditional_inference(self):
        r = self.fit
        self.assertTrue(r.converged)
        self.assertFalse(r.spec.latent_adding_up)
        self.assertEqual(r.sigma.shape, (3, 3))
        self.assertEqual(r.tau.size, 18)
        self.assertTrue(all(p.converged for p in r.probits))
        self.assertGreater(abs(r.coefs.alpha.sum()-1), 1e-6)
        self.assertLess(np.sqrt(np.mean((r.predict()-self.expected)**2)), .035)
        self.assertGreater(np.max(abs(r.predict(kind="latent_shares").sum(axis=1)-1)), .01)
        np.testing.assert_allclose(r.predict(self.frame), r.predict(), atol=1e-12)
        np.testing.assert_allclose(r.predict(kind="residuals"), self.frame[OPTIONS["shares"]]-r.predict())
        np.testing.assert_allclose(r.predict(kind="quantities")*self.frame[OPTIONS["prices"]],
                                   r.predict()*self.frame.m.to_numpy()[:, None])
        self.assertTrue(np.isfinite(r.se).all())
        el, se = r.elasticities_at_means(standard_errors=True)
        np.testing.assert_allclose(el.we, r.elas.we)
        np.testing.assert_allclose(se.income, r.elasticity_se.income, atol=1e-12)
        self.assertEqual(r.coefficient_covariance.shape, (33, 33))
        self.assertIn("Slutsky transformation", r.elasticity_tables())
        self.assertIn("condition on fitted Probits", r.summary())

    def test_logged_inputs_preserve_selection_and_public_quantity_derivatives(self):
        logged = self.frame.copy()
        logged[OPTIONS["prices"]] = np.log(logged[OPTIONS["prices"]])
        logged["m"] = np.log(logged.m)
        fit = translog(logged, OPTIONS["shares"], lnprices=OPTIONS["prices"], lnexpenditure="m",
            demographics=["z"], censor=True, initial=self.fit.theta, sigma_initial=self.fit.sigma, verbose=False)
        np.testing.assert_allclose(fit.tau, self.fit.tau, atol=1e-10)
        np.testing.assert_allclose(fit.predict(), self.fit.predict(), atol=1e-5)
        # Set an evaluation frame to one constant point so its level means are exact.
        point = self.frame.iloc[[0]].copy()
        for name in OPTIONS["prices"]+["m", "z"]:
            point[name] = self.frame[name].mean()
        el = self.fit.elasticities_at_means(point)
        h = 1e-6
        plus, minus = point.copy(), point.copy()
        plus["m"] *= np.exp(h)
        minus["m"] *= np.exp(-h)
        observed = (np.log(self.fit.predict(plus, kind="quantities"))
                    - np.log(self.fit.predict(minus, kind="quantities")))/(2*h)
        np.testing.assert_allclose(el.income, observed[0], atol=1e-8)
        missing = self.frame.iloc[:5].copy()
        missing.loc[2, "z"] = np.nan
        self.assertTrue(np.isnan(self.fit.predict(missing)[2]).all())

    def test_independent_selection_design_and_no_demographics(self):
        fit = translog(self.frame, **dict(OPTIONS, demographics=[], selection_prices=["p3", "p1"],
            selection_expenditure=False, selection_covariates=["z"]), start="mean")
        self.assertTrue(fit.converged)
        self.assertEqual(fit.spec.ndemo, 0)
        self.assertIsNone(fit.selection_layout.expenditure_position)
        self.assertIsNone(fit.selection_layout.price_position(1))
        self.assertEqual(fit.np_prob, 4)
        missing = self.frame.iloc[:5].copy()
        missing.loc[1, "z"] = np.nan
        self.assertTrue(np.isnan(fit.predict(missing)[1]).all())
        self.assertTrue(np.isfinite(fit.predict(missing, kind="latent_shares")).all())

    def test_nested_initialization_keeps_standard_solver_and_full_model(self):
        nested = translog(self.frame, **OPTIONS, start="nested")
        self.assertTrue(nested.converged)
        self.assertEqual(nested.method, "ifgnls")
        self.assertEqual(nested.algorithm, "gn")
        self.assertEqual(nested.stop_rule, "standard")
        self.assertEqual(nested.spec.ndemo, 1)
        self.assertEqual(nested.coefs.nu.shape, (3, 1))
        self.assertFalse(nested.spec.latent_adding_up)
        self.assertTrue(nested.initialization["converged"])
        np.testing.assert_allclose(nested.tau, self.fit.tau, atol=1e-12)
        self.assertLess(np.sqrt(np.mean((nested.predict()-self.expected)**2)), .035)

    def test_nls_and_fgnls_stationarity_uses_the_optimized_covariance(self):
        nls = None
        for method in ("nls", "fgnls"):
            fit = translog(self.frame, **OPTIONS, method=method, initial=self.truth)
            self.assertTrue(fit.converged)
            residual = fit.demand_data.shares-fit.predict()
            J = complex_step_jacobian(lambda t: fitted_shares(t, fit.demand_data, fit.spec), fit.theta)
            J = J.reshape(fit.nobs, 3, fit.spec.n_free)
            if method == "fgnls":
                P = np.linalg.inv(np.linalg.cholesky(nls.sigma))
                residual = residual @ P.T
                J = np.matmul(P, J)
            else:
                nls = fit
            matrix = J.reshape(-1, fit.spec.n_free)
            linear_step = np.linalg.lstsq(matrix, residual.ravel(), rcond=None)[0]
            reduction = np.linalg.norm(matrix @ linear_step)**2/np.linalg.norm(residual)**2
            self.assertAlmostEqual(fit.nrtol, reduction, places=12)
            self.assertTrue(np.isfinite(fit.elasticity_se.income).all())

    def test_full_bootstrap_reestimates_probits_across_serial_and_spawn(self):
        options = dict(OPTIONS, initial=self.fit.theta, sigma_initial=self.fit.sigma,
                       bootstrap_start="warm", reps=3, seed=70)
        serial = translog(self.frame, **options, n_jobs=1)
        spawned = translog(self.frame, **options, n_jobs=2, mp_context="spawn")
        self.assertEqual(serial.boot.reps_ok, 3)
        self.assertEqual(spawned.boot.reps_ok, 3)
        np.testing.assert_allclose(serial.boot.b_star, spawned.boot.b_star, atol=1e-11)
        tau_slice = slice(serial.spec.n_full, serial.n_coefficients)
        self.assertGreater(np.ptp(serial.boot.b_star[:, tau_slice], axis=0).max(), .01)
        self.assertGreater(np.max(abs(serial.V[:serial.spec.n_full, tau_slice])), 1e-6)
        np.testing.assert_allclose(serial.V, serial.boot.V)
        self.assertTrue(np.isfinite(serial.elasticities_at_means(standard_errors=True)[1].income).all())

    def test_selection_validation(self):
        with self.assertRaisesRegex(ValueError, "subset"):
            translog(self.frame, **dict(OPTIONS, selection_prices=["other_price"]))
        with self.assertRaisesRegex(ValueError, "must not repeat"):
            translog(self.frame, **dict(OPTIONS, selection_covariates=["m"]))
        zero = self.frame.copy()
        zero["w2"] = 0
        with self.assertRaisesRegex(ValueError, "no variation"):
            translog(zero, **OPTIONS)
        with self.assertRaises(TypeError):
            translog(self.frame, **OPTIONS, ivexp=["z"])


if __name__ == "__main__":
    unittest.main()
